# Generated by Django 5.2.4 on 2025-11-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='national_id_document',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/national_ids/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='proof_of_savings_document',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/proof_of_savings/'),
        ),
    ]
