# Generated by Django 5.2.4 on 2025-11-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_national_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_period',
            field=models.IntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months')], default=6),
        ),
    ]
