# Generated by Django 5.2.4 on 2025-11-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='national_ids/'),
        ),
    ]
