# Generated by Django 5.2.4 on 2025-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameya',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
