# Generated by Django 5.2.4 on 2025-11-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameya', '0002_gameya_max_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameya',
            name='start_date',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
