# Generated by Django 5.2.4 on 2025-11-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameya', '0003_gameya_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameya',
            name='next_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
